# Generated by Django 5.1.4 on 2025-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='描述')),
                ('emoji', models.CharField(max_length=255, verbose_name='Emoji')),
                ('type', models.CharField(choices=[('STYLE', '風格類標籤'), ('TECHNIQUE', '技術類標籤'), ('COLOR', '色彩分類標籤'), ('OCCASION', '場合用途標籤'), ('PRICE', '價格層次標籤'), ('TARGET_AUDIENCE', '目標客群標籤')], db_index=True, max_length=255, verbose_name='類型')),
            ],
            options={
                'verbose_name': '店家標籤',
                'verbose_name_plural': '店家標籤',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='店家名稱')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('phone', models.CharField(max_length=255, verbose_name='電話')),
                ('review_count', models.IntegerField(default=0, verbose_name='總評論數')),
                ('website', models.URLField(blank=True, null=True, verbose_name='官方網站')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='評分')),
                ('reviews', models.TextField(blank=True, null=True, verbose_name='評論')),
                ('price_and_service', models.TextField(blank=True, null=True, verbose_name='價格與服務')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='AI 摘要')),
                ('tags', models.ManyToManyField(blank=True, related_name='shops', to='cms.shoptag', verbose_name='店家標籤')),
            ],
            options={
                'verbose_name': '時間戳',
                'verbose_name_plural': '時間戳',
                'abstract': False,
            },
        ),
    ]
