# Generated by Django 5.1.4 on 2025-03-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.TextField(verbose_name='圖片路徑')),
            ],
            options={
                'verbose_name': '時間戳',
                'verbose_name_plural': '時間戳',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '店家資訊', 'verbose_name_plural': '店家資訊'},
        ),
        migrations.AlterField(
            model_name='shoptag',
            name='type',
            field=models.CharField(choices=[('STYLE', '風格類'), ('TECHNIQUE', '技術類'), ('PRICE', '價格'), ('ENVIRONMENT', '環境氛圍'), ('TRANSPORTATION', '交通便利'), ('TARGET_AUDIENCE', '目標客群')], db_index=True, max_length=255, verbose_name='類型'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_path', models.TextField(verbose_name='封面圖片路徑')),
                ('content', models.TextField(verbose_name='內容')),
                ('url', models.URLField(blank=True, null=True, verbose_name='網址')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.TextField(verbose_name='圖片路徑')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.article')),
            ],
            options={
                'verbose_name': '文章圖片',
                'verbose_name_plural': '文章圖片',
            },
        ),
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.TextField(verbose_name='圖片路徑')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cms.shop')),
            ],
            options={
                'verbose_name': '店家照片',
                'verbose_name_plural': '店家照片',
            },
        ),
    ]
