# Generated by Django 5.1.4 on 2025-03-12 00:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepagebanner_alter_shop_options_alter_shoptag_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='內容'),
        ),
    ]
