# Generated by Django 5.1.4 on 2025-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='ai_summary',
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='查詢用，例如：台北市、新北市', max_length=20, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='shop',
            name='core_features',
            field=models.TextField(blank=True, null=True, verbose_name='核心特色'),
        ),
        migrations.AddField(
            model_name='shop',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='查詢用，例如：大安區、中山區', max_length=20, null=True, verbose_name='行政區'),
        ),
        migrations.AddField(
            model_name='shop',
            name='recommended_uses',
            field=models.TextField(blank=True, null=True, verbose_name='推薦用途'),
        ),
        migrations.AddField(
            model_name='shop',
            name='review_summary',
            field=models.TextField(blank=True, null=True, verbose_name='評論摘要'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(help_text='完整地址，用於前端顯示', verbose_name='完整地址'),
        ),
    ]
