# Generated by Django 5.1.4 on 2025-03-15 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_shop_ai_summary_shop_city_shop_core_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebanner',
            options={'verbose_name': '首頁Banner', 'verbose_name_plural': '首頁Banner'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover_path',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='縮圖路徑'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='內容'),
        ),
    ]
