# Generated by Django 5.1.4 on 2025-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_homepagebanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='最高價格'),
        ),
        migrations.AddField(
            model_name='shop',
            name='price_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='最低價格'),
        ),
    ]
