# Generated by Django 5.1.4 on 2025-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_shop_price_max_shop_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='營業時間'),
        ),
    ]
