# Generated by Django 5.1.4 on 2025-04-06 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_shop_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='core_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='核心特色'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_and_service',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='價格與服務'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='recommended_uses',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='推薦用途'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='review_summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='評論摘要'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reviews',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='評論'),
        ),
    ]
